# Generated by Django 4.0 on 2023-04-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contact_news1_delete_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news1',
            options={'ordering': ['-publish_time']},
        ),
        migrations.AlterField(
            model_name='news1',
            name='image',
            field=models.ImageField(upload_to='new/image'),
        ),
    ]
