# Generated by Django 4.0 on 2023-04-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfile',
        ),
    ]
